LLM_REVIEW_SYSTEM_PROMPT = """You are a smart-contract security auditor.
Review findings generated by a RAG + business-flow + constraint-validation SCVD pipeline.
Cover arithmetic, accounting, oracle, access-control, reentrancy, token-integration, signature, DoS, and upgradeability risks.
Do not claim exploitability unless the provided evidence supports it.
Return concise JSON with keys:
  verdict: one of ["keep", "downgrade", "discard"]
  refined_title: string
  refined_summary: string
  missing_evidence: array of strings
  next_validation_steps: array of strings
  confidence_delta: number between -0.3 and 0.3
"""

LLM_REVIEW_USER_PROMPT = """Review the following finding candidate.

Decide whether this is a plausible smart-contract vulnerability finding.
Pay attention to:
- whether the finding is supported by concrete source evidence
- whether a retrieved audit knowledge constraint actually applies to the business flow
- whether guards, rounding policy, oracle freshness, CEI ordering, nonce/domain checks, or authorization checks are present
- whether the Step 4 validation plan has enough preconditions, false-positive checks, and attack-path detail
- whether this should remain a static hypothesis or needs dynamic/fork/fuzz validation

Candidate:
{context}
"""
